name: VoxEnchanting
description: The Enchanting Plugin
main: com.qualityplus.enchanting.VoxEnchanting
version: ${version}
api-version: 1.13
authors: [QualityPlus]
load: POSTWORLD
depend: [TheAssistant]
softdepend: [EcoEnchants, AdvancedEnchantments]
commands:
  theenchanting:
    aliases: ["voxenchanting", "enchanting", "theench"]
    description: Enchanting's main command